apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
    app.kubernetes.io/instance: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      targetPort: 3306
      port: 3306
